<?php
// Receive the POST request from Supabase Send SMS Hook
$payload = json_decode(file_get_contents('php://input'), true);

// Verify the payload from Supabase
if (!$payload || !isset($payload['phone']) || !isset($payload['code'])) {
    http_response_code(400);
    echo json_encode(["error" => "Invalid payload"]);
    exit;
}

$phone = $payload['phone']; // Supabase sends phone as +91XXXXXXXXXX
$otp = $payload['code']; // The 6-digit OTP generated by Supabase

// The SMS Gateway expects the number without the '+' sign (e.g., 91XXXXXXXXXX)
$formatted_phone = str_replace('+', '', $phone);

// ==========================================
// ⚠️ ENTER YOUR INNUVIS CREDENTIALS BELOW ⚠️
// ==========================================
$user = "YOUR_USERNAME";        // Replace with your Innuvis username (or API Key)
$password = "YOUR_PASSWORD";    // Replace with your Innuvis password
$senderid = "YOUR_SENDER_ID";   // Your 6-character DLT Approved Sender ID (e.g., AMPLRH)
$route = "YOUR_ROUTE_ID";       // Your Route ID from the dashboard
$peid = "YOUR_PEID";            // Your DLT Entity PEID
$templateid = "YOUR_TEMPLATE_ID"; // Your DLT Template ID for OTPs
// ==========================================

// Your approved DLT message template. Make sure this EXACTLY matches your approved DLT template!
// Example: "Your OTP for login is {#var#}. Do not share this."
$message = "Your AMPLR Health verification code is " . $otp . ". Do not share this with anyone.";
$text = urlencode($message);

// Construct the Innuvis API URL
$url = "http://sms.innuvissolutions.com/api/mt/SendSMS?user={$user}&password={$password}&senderid={$senderid}&channel=Trans&DCS=0&flashsms=0&number={$formatted_phone}&text={$text}&route={$route}&Peid={$peid}&DLTTemplateId={$templateid}";

// Send the HTTP Request to the SMS Gateway
$response = file_get_contents($url);

// Return success to Supabase so it knows the SMS was sent
if ($response) {
    http_response_code(200);
    echo json_encode(["success" => true, "gateway_response" => json_decode($response)]);
} else {
    http_response_code(500);
    echo json_encode(["error" => "Failed to connect to SMS Gateway"]);
}
?>
